from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session
from app.services.generation_service import get_all_floorplans, get_recent_floorplans
from app.db.session import get_db
from app.schemas.generation import GenerationResponse
from typing import List, Optional
from app.api.deps import get_current_user
from app.db import crud
from datetime import datetime, timedelta
from sqlalchemy import desc, asc, func
from app.models.user import User

router = APIRouter()

@router.get("/", response_model=List[GenerationResponse])
def read_floorplans(
    db: Session = Depends(get_db),
    page: int = Query(1, ge=1),  
    limit: int = Query(20, le=50),
    sort: str = Query("newest", regex="^(newest|oldest)$"),
    date: Optional[str] = None,
):
    """
    Get all floor plans with pagination, sorting and date filtering.
    """
    skip = (page - 1) * limit
    
    # Base query
    query = db.query(crud.Generation)
    
    # Apply date filter if provided
    if date:
        try:
            filter_date = datetime.strptime(date, "%Y-%m-%d").date()
            # Filter for the specific day by using the start and end of the day
            start_of_day = datetime.combine(filter_date, datetime.min.time())
            end_of_day = datetime.combine(filter_date, datetime.max.time())
            query = query.filter(
                crud.Generation.created_at >= start_of_day,
                crud.Generation.created_at <= end_of_day
            )
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD")
    
    # Apply sorting
    if sort == "newest":
        query = query.order_by(desc(crud.Generation.created_at))
    else:
        query = query.order_by(asc(crud.Generation.created_at))
    
    # Apply pagination
    generations = query.offset(skip).limit(limit).all()
    
    return [
        GenerationResponse(
            id=g.id,
            prompt=g.prompt,
            layout_image_url=g.layout_image_url,
            sd_image_url=g.sd_image_url,
            created_at=g.created_at,
            status=g.status,
            error_message=g.error_message
        )
        for g in generations
    ]

@router.get("/recent", response_model=List[GenerationResponse])
def read_recent_floorplans(
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user),
    limit: int = Query(5, le=50),
):
    return get_recent_floorplans(db, current_user.id, limit)

@router.get("/my", response_model=List[GenerationResponse])
def read_my_floorplans(
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user),
    page: int = Query(1, ge=1),
    limit: int = Query(20, le=50),
    sort: str = Query("newest", regex="^(newest|oldest)$"),
):
    """
    Get all floor plans generated by the current user.
    """
    print(f"Fetching floorplans for user {current_user.id}")
    print(f"Sort parameter received: {sort}")
    skip = (page - 1) * limit
    
    # Base query
    query = db.query(crud.Generation).filter(crud.Generation.user_id == current_user.id)
    
    # Apply sorting
    if sort == "newest":
        print("Applying DESC order (newest first)")
        query = query.order_by(desc(crud.Generation.created_at))
    else:
        print("Applying ASC order (oldest first)")
        query = query.order_by(asc(crud.Generation.created_at))
    
    generations = query.offset(skip).limit(limit).all()
    
    print(f"Found {len(generations)} generations")
    if generations:
        print(f"First generation date: {generations[0].created_at}")
        print(f"Last generation date: {generations[-1].created_at}")
    for g in generations:
        print(f"Generation {g.id}: {g.prompt}")
    
    return [
        GenerationResponse(
            id=g.id,
            prompt=g.prompt,
            layout_image_url=g.layout_image_url,
            sd_image_url=g.sd_image_url,
            created_at=g.created_at,
            status=g.status,
            error_message=g.error_message
        )
        for g in generations
    ]

@router.delete("/{generation_id}", response_model=dict)
def delete_floorplan(
    generation_id: int,
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """
    Delete a floor plan. Only the owner can delete their own floor plans.
    """
    generation = db.query(crud.Generation).filter(
        crud.Generation.id == generation_id,
        crud.Generation.user_id == current_user.id
    ).first()
    
    if not generation:
        raise HTTPException(status_code=404, detail="Floor plan not found or you don't have permission to delete it")
    
    db.delete(generation)
    db.commit()
    
    return {"message": "Floor plan deleted successfully"}

@router.get("/stats/public")
def get_public_stats(db: Session = Depends(get_db)):
    """
    Get public statistics for the home page.
    """
    try:
        # Total generations
        total_generations = db.query(func.count(crud.Generation.id)).scalar()
        
        # Total users
        total_users = db.query(func.count(User.id)).scalar()
        
        # Success rate (generations with status 'success')
        success_count = db.query(func.count(crud.Generation.id)).filter(
            crud.Generation.status == 'success'
        ).scalar()
        
        success_rate = round((success_count / total_generations * 100) if total_generations > 0 else 0, 1)
        
        return {
            "total_generations": total_generations,
            "total_users": total_users,
            "success_rate": success_rate
        }
    except Exception as e:
        print(f"Error getting public stats: {e}")
        return {
            "total_generations": 0,
            "total_users": 0,
            "success_rate": 0
        }

@router.get("/stats/user")
def get_user_stats(
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    """
    Get user statistics for the home page (all floorplans without pagination).
    """
    try:
        # Get all user's floorplans without pagination
        all_generations = db.query(crud.Generation).filter(
            crud.Generation.user_id == current_user.id
        ).order_by(desc(crud.Generation.created_at)).all()
        
        # Calculate recent floorplans (last 7 days)
        one_week_ago = datetime.now() - timedelta(days=7)
        recent_generations = [g for g in all_generations if g.created_at > one_week_ago]
        
        # Calculate success rate
        successful_generations = [g for g in all_generations if g.status == 'success']
        success_rate = round((len(successful_generations) / len(all_generations) * 100) if all_generations else 0, 1)
        
        # Get recent floorplans for display (first 3)
        recent_for_display = all_generations[:3]
        
        return {
            "total_blueprints": len(all_generations),
            "recent_count": len(recent_generations),
            "success_rate": success_rate,
            "successful_blueprints": len(successful_generations),
            "recent_blueprints": [
                {
                    "id": g.id,
                    "prompt": g.prompt,
                    "layout_image_url": g.layout_image_url,
                    "sd_image_url": g.sd_image_url,
                    "created_at": g.created_at.isoformat(),
                    "status": g.status
                }
                for g in recent_for_display
            ]
        }
    except Exception as e:
        print(f"Error getting user stats: {e}")
        return {
            "total_blueprints": 0,
            "recent_count": 0,
            "success_rate": 0,
            "successful_blueprints": 0,
            "recent_blueprints": []
        }